### ISSUE TITLE
Cannot install on CentOS 7 with gcc 4.8.5

### ISSUE THREAD

**Issue by shlagbaum** [tnagler/RcppThread#13]
Is it available on CentOS?
When tried to install got the following:

* installing *source* package ‘RcppThread’ ...
** package ‘RcppThread’ successfully unpacked and MD5 sums checked
** libs
g++ -m64 -std=gnu++11 -I/usr/include/R -DNDEBUG -I../inst/include/ -pthread -I"/usr/lib64/R/library/Rcpp/include" -I/usr/local/include   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
In file included from ../inst/include/RcppThread.h:10:0,
                 from RcppExports.cpp:4:
../inst/include/RcppThread/Thread.hpp: In lambda function:
../inst/include/RcppThread/Thread.hpp:49:19: error: parameter packs not expanded with ‘...’:
                 f(args...);
                   ^
../inst/include/RcppThread/Thread.hpp:49:19: note:         ‘args’
../inst/include/RcppThread/Thread.hpp:49:23: error: expansion pattern ‘args’ contains no argument packs
                 f(args...);
                       ^
In file included from ../inst/include/RcppThread.h:11:0,
                 from RcppExports.cpp:4:
../inst/include/RcppThread/ThreadPool.hpp: In member function ‘std::future<decltype (f(args ...))> RcppThread::ThreadPool::push(F&&, Args&& ...)’:
../inst/include/RcppThread/ThreadPool.hpp:86:22: error: expected ‘,’ before ‘...’ token
             [&f, args...] { return f(args...); }
                      ^
../inst/include/RcppThread/ThreadPool.hpp:86:22: error: expected identifier before ‘...’ token
../inst/include/RcppThread/ThreadPool.hpp:86:25: error: parameter packs not expanded with ‘...’:
             [&f, args...] { return f(args...); }
                         ^
../inst/include/RcppThread/ThreadPool.hpp:86:25: note:         ‘args’
../inst/include/RcppThread/ThreadPool.hpp: In lambda function:
../inst/include/RcppThread/ThreadPool.hpp:86:42: error: expansion pattern ‘args’ contains no argument packs
             [&f, args...] { return f(args...); }
                                          ^
In file included from ../inst/include/RcppThread.h:10:0,
                 from RcppExports.cpp:4:
../inst/include/RcppThread/Thread.hpp: In instantiation of ‘struct RcppThread::Thread::Thread(Function&&, Args&& ...) [with Function = RcppThread::ThreadPool::ThreadPool(size_t)::__lambda5; Args = {}]::__lambda4’:
../inst/include/RcppThread/Thread.hpp:50:9:   required from ‘RcppThread::Thread::Thread(Function&&, Args&& ...) [with Function = RcppThread::ThreadPool::ThreadPool(size_t)::__lambda5; Args = {}]’
/usr/include/c++/4.8.2/ext/new_allocator.h:120:4:   required from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = RcppThread::Thread; _Args = {RcppThread::ThreadPool::ThreadPool(size_t)::__lambda5}; _Tp = RcppThread::Thread]’
/usr/include/c++/4.8.2/bits/alloc_traits.h:254:4:   required from ‘static typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type std::allocator_traits<_Alloc>::_S_construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = RcppThread::Thread; _Args = {RcppThread::ThreadPool::ThreadPool(size_t)::__lambda5}; _Alloc = std::allocator<RcppThread::Thread>; typename std::enable_if<std::allocator_traits<_Alloc>::__construct_helper<_Tp, _Args>::value, void>::type = void]’
/usr/include/c++/4.8.2/bits/alloc_traits.h:393:57:   required from ‘static decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) std::allocator_traits<_Alloc>::construct(_Alloc&, _Tp*, _Args&& ...) [with _Tp = RcppThread::Thread; _Args = {RcppThread::ThreadPool::ThreadPool(size_t)::__lambda5}; _Alloc = std::allocator<RcppThread::Thread>; decltype (_S_construct(__a, __p, (forward<_Args>)(std::allocator_traits::construct::__args)...)) = <type error>]’
/usr/include/c++/4.8.2/bits/vector.tcc:97:40:   required from ‘void std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {RcppThread::ThreadPool::ThreadPool(size_t)::__lambda5}; _Tp = RcppThread::Thread; _Alloc = std::allocator<RcppThread::Thread>]’
../inst/include/RcppThread/ThreadPool.hpp:62:13:   required from here
../inst/include/RcppThread/Thread.hpp:49:19: error: using invalid field ‘RcppThread::Thread::Thread(Function&&, Args&& ...)::__lambda4::__args’
                 f(args...);
                   ^
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘RcppThread’

**Comment by tnagler** [comment]
Hm, this is weird, my usage of parameter packs is pretty standard and should be supported by a c++11-compatible compiler (and gcc 4.8.5 should be such). Unfortunately, I have no way of testing on CentOS myself, but think it's unlikely to be an issue of the operating system.  Could you try with a different (or more recent) compiler?

**Comment by shlagbaum** [comment]
Yep, that helped, thanks. Updated gcc as instructed here: https://stackoverflow.com/questions/36327805/how-to-install-gcc-5-3-with-yum-on-centos-7-2:
gcc --version
gcc (GCC) 7.2.1 20170829 (Red Hat 7.2.1-1)
Copyright (C) 2017 Free Software Foundation, Inc.

**Comment by tnagler** [comment]
Cool, have fun with the package!
