### ISSUE TITLE
Polymorphic lambdas

### ISSUE THREAD

**Issue by jwood000** [tnagler/RcppThread#34]
Hey Thomas,

First off, awesome package. This has been a great inspiration. 

Secondly, I've been trying to implement `RcppThread` into the next release of `RcppAlgos`, but I'm having difficulties building with templated functions on all compilers (specifically gcc). Currently, I have successfully been able to build on all platforms/compilers (as tested on `rhub` and `win-builder`) using `std::thread/future` from the standard library with templated functions like the following:

```
#include <thread>

template <typename T>
void someFunc(int strtIndex, int endIndex, std::vector<T> &x) {
    \\ do some intense computation
}

template <typename T>
void parallelCall(std::vector<T> &x, int chunk) {
    std::vector<std::thread> myThreads;
    int nThreads = std::thread::hardware_concurrency();
    int m = 0;
    int n = chunk;

    for (int i = 0; i < nThreads; ++i, m = n + 1, n += chunk) {
        myThreads.emplace_back(someFunc<T>, m, n, std::ref(x));
    }

    for (auto &thr: myThreads)
        thr.join();
}
```

The problem comes in when I try to convert this to `RcppThread`.

```
#include <RcppThread.h>

template <typename T>
void someFunc(int strtIndex, int endIndex, std::vector<T> &x) {
    \\ do some intense computation
}

template <typename T>
void parallelCall(std::vector<T> &x, int chunk) {
    RcppThread::ThreadPool pool;
    int nThreads = std::thread::hardware_concurrency();
    int m = 0;
    int n = chunk;

    for (int i = 0; i < nThreads; ++i, m = n + 1, n += chunk) {
        pool.push(someFunc<T>, m, n, std::ref(x));
    }

    pool.join();
}
```

The above builds fine and passes all of my unit tests on `clang`. However, when I build a `tar.gz` file and upload to `win-builder` which uses `gcc-4.9.3/mingw_32/bin/g++` I'm getting the following error:

```
d:/RCompile/CRANpkg/lib/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:127:36: error: variable 'f' has function type
         jobs_.emplace([f, args...] { f(args...); });
```

So I tried converting my functions to stand alone lambdas like you have in your vignette (only mine have templates... You will note that in my `Makevars` file, I am using `CXX_STD = CXX14` as using `CXX11` gives the warning `variable templates are a C++14 extension`). So I would have something like the following:

```
#include <RcppThread.h>

template <typename T>
auto someFunc = [] (int strtIndex, int endIndex, std::vector<T> &x) {
    \\ do some intense computation
}

template <typename T>
void parallelCall(std::vector<T> &x, int chunk) {
    RcppThread::ThreadPool pool;
    int nThreads = std::thread::hardware_concurrency();
    int m = 0;
    int n = chunk;

    for (int i = 0; i < nThreads; ++i, m = n + 1, n += chunk) {
        pool.push(someFunc<T>, m, n, std::ref(x));
    }

    pool.join();
}
```

Again this builds fine on `clang`, but I get the following errors from `win-builder`:

```
error: template declaration of 'auto PrimeSieve::PrimeSieveSmall'
.
.
error: 'PrimeSieveBig' was not declared in this scope
                     pool.push(PrimeSieveBig<typePrime>, lowerBnd, upperBnd, std::ref(svPriOne),
                               ^
../inst/include/EratosthenesSieve.h:619:54: error: expected primary-expression before '>' token
                     pool.push(PrimeSieveBig<typePrime>, lowerBnd, upperBnd, std::ref(svPriOne),
                                                      ^
../inst/include/EratosthenesSieve.h:619:55: error: expected primary-expression before ',' token
                     pool.push(PrimeSieveBig<typePrime>, lowerBnd, upperBnd, std::ref(svPriOne),
```

I found this [stackoverflow post](https://stackoverflow.com/q/34815698/4408538) that has some similarities.

I know `C++14` supports polymorphic lambdas via the use of the keyword `auto`, however this doesn't play nicely when replacing `std::vector<T> x` with `auto x` (and `std::vector<auto>` is illegal currently.. I think `C++20` will support this) as any code in the calling function that refers to any member function of `std::vector` throws errors on `clang`.  For example:

```
no member named 'push_back' in 'std::__1::reference_wrapper<stdLL__1::vector<long long, std::__1::allocator<long long> > >'
```

I will also run into to similar issues with other functions that pass `std::vector<std::vector<T>>`.

Anywho, I know I can simply write separate non-templated lambdas (I have done this and built successfully on `rhub` and `win-builder`), but I feel like there is a more elegant solution. If I have to, I will do this for the sake of thread safety. As you say in your vignette: _"In any case, the main advantage is automatic and safe synchronization with R, i.e., usability and not speed."_

Again, thanks again for all of your great work and any help would be greatly appreciated.

Regards,
Joseph

**Comment by tnagler** [comment]
Hi Joseph, great to hear that you like the library. 

Not sure how much more complex your real code is, but wrapping the function into a `std::cref` seems to do the trick for me. 
``` cpp
pool.push(std::cref(someFunc<T>), m, n, std::ref(x));
```
(should work with your first version and C++11)

Best,
Thomas

**Comment by jwood000** [comment]
Hey Thomas,

This is great. I have implemented this and have successfully passed win-builder checks.  I will make a commit tp `RcppAlgos` in a few days with all of the `RcppThread` updates. I'm very excited.

Thanks again for all of your help!!

Joseph

P.S. I'm not sure if I should close this issue or leave it to you. I'm saying this because I want to follow the proper etiquette.

**Comment by tnagler** [comment]
I'm very happy to hear that things worked out. 

P.S.: I grant you permission to close future issues yourself ;)
