### ISSUE TITLE
Consider removing ThreadPool's move assignment operator

### ISSUE THREAD

**Issue by asardaes** [tnagler/RcppThread#35]
If I compile with Clang, I get the following warning:

```
.../3.6/RcppThread/include/RcppThread/ThreadPool.hpp:37:17: warning: explicitly defaulted move assignment operator is implicitly deleted [-Wdefaulted-function-deleted]
    ThreadPool& operator=(ThreadPool&& other) = default;
                ^
.../R/x86_64-pc-linux-gnu-library/3.6/RcppThread/include/RcppThread/ThreadPool.hpp:77:16: note: move assignment operator of 'ThreadPool' is implicitly deleted because field 'mTasks_' has a deleted move assignment operator
    std::mutex mTasks_;
               ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../include/c++/9.1.0/bits/std_mutex.h:95:12: note: 'operator=' has been explicitly marked deleted here
    mutex& operator=(const mutex&) = delete;
           ^
1 warning generated.
```

**Comment by tnagler** [comment]
Good catch, thanks! Should be fixed by #36 .

**Comment by mpadge** [comment]
@tnagler Could you please update your CRAN version to reflect the above-referenced commit? The warnings persist with current CRAN version, which could be a problem for submissions which link to `RcppThread`. Although they are only generated by `clang++`, and do not appear with `g++`, and although all standard CRAN tests, including asan/ubsan, use the latter, it may nevertheless be possible that manual inspection tests may use `clang++` and so lead to failure. It basically makes linking to this package a risk until the CRAN version is update. Some movement on that front would be appreciated, please! Thanks for the great package!

**Comment by tnagler** [comment]
@mpadge New version is on it's way to CRAN. Sorry for the delay, it's hard to keep track of all the packages ;)
