### ISSUE TITLE
avoid "Not imported from" Note by exposing dummy function

### ISSUE THREAD

**Issue by mpadge** [tnagler/RcppThread#38]
Thanks for the great package which provides much needed functionality for long-running parallel jobs - very much appreciated! This is not a complaint, but ... current CRAN checks for [`dodgr` package](https://cran.r-project.org/web/checks/check_results_dodgr.html) trigger a Note:

>     Namespace in Imports field not imported from: ‘RcppThread’
>     All declared Imports should be used. 

Could you expose a dummy function like `Rcpp` does with `evalCpp`, and `RcppParallel` does with `RcppParallelLibs`, in order to suppress the note by allowing the package to import *something* into the NAMESPACE?

**Comment by tnagler** [comment]
Thanks for the kind words!

It should be enough to have `LinkingTo: RcppThread` and drop it from the `Import`s. Let me know if this doesn't work.

**Comment by mpadge** [comment]
Looks good - thanks!
