### ISSUE TITLE
Feature request: thread safe equivalent to Rcpp::stop()

### ISSUE THREAD

**Issue by TommyJones** [tnagler/RcppThread#39]
Per, [this question on stackoverflow](https://stackoverflow.com/questions/63107996/what-is-a-thread-safe-way-to-throw-an-error-while-using-rcpp), it would be great to have a thread safe way to throw errors with a single function call, similar to what you've done with `RcppThread::Rcout`and `RcppThread::checkUserInterrupt`.

I'd imagine it going something like this:

```
#include <RcppThread.h>
// [[Rcpp::plugins(cpp11)]]
// [[Rcpp::depends(RcppThread)]]

void myfun() {

  // parallel loop
  RcppThread::parallelFor(0, 100, [](int j){
    // do something that causes an error
    if (error_condition) {
          RcppThread::stop("You did a bad thing.");
    }
    // do other things
  });

}
```

Thanks for considering this. Great package, BTW!

**Comment by tnagler** [comment]
You can throw any C++ exception in your code, for example 
``` cpp
throw std::runtime_error("You did a bad thing");
```
or more generally
``` cpp
throw Exception;
```
where `Exception` is an object inherting from [`std::exception`](https://en.cppreference.com/w/cpp/error/exception).

This is what happens under the hood: 
1. The higher-lever abstractions in RcppThread (everything `ThreadPool`, `parallelFor`, `parallelForeach`) store the exception temporarily in an [`std::exception_ptr`](https://en.cppreference.com/w/cpp/error/exception_ptr).
2. All scheduled (but not yet running) tasks are canceled.
3. After all threads have "stopped", the original exception is re-thrown from the main thread.
4. Rcpp does its magic to convert the C++ exception into an R error.

**Comment by TommyJones** [comment]
Ah! Much easier than I expected. I thought I was going to have to manage
that all myself.

I'll point to your response as an answer to my SO question.

Thank you!
