### ISSUE TITLE
Incompatible with C++14?

### ISSUE THREAD

**Issue by fangzhou-xie** [tnagler/RcppThread#40]
Thanks for this wonderful package! I have been playing with this package recently and believe it could have great potentials for people who want their codes to be even faster!

As I was using it, I had run into a problem where it seems the codes would be fine with C++11 but not C++14. I wonder if this is because of compatibility issues?

To replicate this, please run the following code:

```
Rcpp::cppFunction('std::vector<double> tt(std::vector<std::string> strings) {
  
  std::vector<double> vec1(strings.size());
  std::vector<double> vec2(strings.size());
  std::vector<double> vec3(strings.size());
  std::vector<double> vec4(strings.size());
  
  RcppThread::ThreadPool pool(2);
  
  pool.parallelFor(0, strings.size(), [&] (unsigned int i) {
    // double tensor[] = {1.5, 2.0};
    std::vector<double> tensor = {1.5, 2.0, 3.5, 4.0};
    for (std::size_t j = 0; j < tensor.size(); j++) {
      switch(j) {
      case 0:
        vec1[i] = tensor[j];
      case 1:
        vec2[i] = tensor[j];
      case 2:
        vec3[i] = tensor[j];
      case 3:
        vec4[i] = tensor[j];
      }
    }
  });
  
  return(vec1);
}', depends = "RcppThread", plugins = "cpp14")
```

And then after compilation:

```
tt(c("lsijfsl", "jlije"))
```

At least for me, my R session will crash and abort.

**Comment by tnagler** [comment]
I could replicate the issue and after some digging I found that the mistake is your code example :) 

Before returning from the function you have to call `pool.join()` or `pool.wait()` to start synchronizing, as explained in Section 4 of the [RcppThread paper](https://www.jstatsoft.org/index.php/jss/article/view/v097c01/v97c01.pdf). 

It seems like a (un)lucky coincidence that the C++11 version let you get away with it.

**Comment by fangzhou-xie** [comment]
Aha! Of course, if I return before the pool is joined there will be error! (Apparently I am not reading the manual carefully. And it somehow works with C++11 :) )

Thanks a lot!
