### ISSUE TITLE
Print to stderr

### ISSUE THREAD

**Issue by appelmar** [tnagler/RcppThread#59]
Thanks for the nice package, which I'd like to use in my package instead of `RcppProgress` and some custom locking code. 

Thereby, I'd like to print some diagnostic messages and a progress bar to stderr instead of stdout. Do I overlook anything and is this already possible? If not, would this be of interest to the package? Maybe simply copying and adapting Rcout.hpp and `RMonitor::safelyPrint()` would be enough? Many thanks!

**Comment by tnagler** [comment]
You are right: it's not yet possible, but should be easy to implement with a bit of copy&paste. Teaching over here started this week, so I don't have much time right now. Happy to accept a pull request though ;)

**Comment by appelmar** [comment]
Great, working on it.

**Comment by tnagler** [comment]
Thanks a lot for your work, when would you need this on CRAN?

**Comment by appelmar** [comment]
I plan to submit an update of my package to CRAN in March / April. Would be great if RcppThread has been updated then but no problem, if not (I see that version 2.0.2 has just landed on CRAN a few days ago).

**Comment by tnagler** [comment]
Updated version is on its way to CRAN.
