### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by Be4UChoose2Exit** [tnagler/RcppThread#65]
Hi When I install dtwclust on rweb services, I am getting this error:
(sorry for the image because I am not allowed to copy the codes from this environment)
<img width="651" alt="屏幕截图 2022-06-14 103353" src="https://user-images.githubusercontent.com/26829002/173481517-983d517b-20ba-48e1-9876-bbdb8dafa86c.png">
<img width="652" alt="屏幕截图 2022-06-14 103447" src="https://user-images.githubusercontent.com/26829002/173481534-15332162-ccda-428d-9aae-73bfac428fc2.png">

I am using gcc version of 8.3 and down below is my environment info:
<img width="258" alt="屏幕截图 2022-06-14 103902" src="https://user-images.githubusercontent.com/26829002/173481894-fef73b16-d9fd-4e28-8dce-afcac2eceb9a.png">

Thanks!

**Comment by tnagler** [comment]
I'm pretty sure R is not using gcc 8.3 here, since both errors indicate that the compiler is not fully C++11 compliant:
- The parameter packs problem, see e.g., #13.
- [std::align](https://en.cppreference.com/w/cpp/memory/align) is part of the standard library since C++11.
