### ISSUE TITLE
Access to buffer

### ISSUE THREAD

**Issue by pommedeterresautee** [tnagler/RcppThread#7]
In my package I need to access to buffer to override existing call to cout (it s a wrapper, I won t change the original source code)
So I do something like : 
```C++
std::ostream Rcout(Rcpp::Rcout.rdbuf());
```
Rprinter seems to have not such method. 
What can I do?

Code available [there](https://github.com/pommedeterresautee/fastrtext/blob/master/src/r_compliance.cc)

**Comment by tnagler** [comment]
Hi, just to make sure we're on the same page:
- you don't want to alter the code, but want the behavior of `RcppThread::Rcout` whenever `std::cout` is called.
- to do this, you redefine `cout` as `Rcout` with a preprocessor macro and create a new object called `Rcout` in namespace `std`.


In this case,  the following should do to the trick: In `r_compliance.h`, replace
``` cpp
namespace std {
  extern std::ostream Rcout;
}
```
with
``` cpp
#include "RcppThread/Rcout.hpp"
namespace std {
  extern RcppThread::RPrinter Rcout;
}
```
and remove the corresponding lines in `r_compliance.cc`.

**Comment by pommedeterresautee** [comment]
Thanks !! This is working as expected (compiles and print only at the end when use in a multithread environment).
I thought the main thread would be called from time to time during the learning and would clean the new Rcout buffer (during learning Rcout is mainly used to print progress, so every few milli seconds a new line is added to replace the precedent with a new progress info). Unfortunately this is not the case and the program crash (the memory reach several hundred of Mb).

Following your Vignette, I thought I would do the same thing with the std:thread (and replace it with Thread):

```C++
...
#define exit(status_code) exit_fasttext(status_code)
#define cerr Rcout // with cerr, no line refresh possible on R (it is an issue for learning with verbose set to 2, progress line is updated)
#define cout Rcout
#define thread Rthread
#define main main_fastrtext // no direct call to main(), otherwise Cran complains + strange errors

// catch the call to exit and call Rcpp::stop() when there is a fail
void exit_fasttext(int error_code);

// Copy of Rcout in std namespace to reroute cout to R terminal with a macro
namespace std {
  extern RcppThread::RPrinter Rcout;
  extern RcppThread::Thread Rthread;
}
```

But I got compilation error : 
![image](https://user-images.githubusercontent.com/1029874/32416740-862d12ae-c24e-11e7-8313-f6162f0d1a30.png)

Do you have an idea on how I should proceed for thread?

**Comment by tnagler** [comment]
The line
``` cpp
  extern RcppThread::Thread Rthread;
```
should probably be
``` cpp
  typedef RcppThread::Thread Rthread;
```

**Comment by pommedeterresautee** [comment]
Thanks!!!!! It works!!!! You just solved my biggest issue on this project. Really thank you!

**Comment by tnagler** [comment]
Glad I could help!
