### ISSUE TITLE
Compilation used the following non-portable flag(s):   ‘-Wno-missing-template-arg-list-after-template-kw’ including flag(s) suppressing warnings

### ISSUE THREAD

**Issue by SpatLyu** [tnagler/RcppThread#76]
I created an [R package](https://github.com/stscl/itmsa) using `Rcpp` and `RcppThread`. In the Makefiles, I only used `PKG_LIBS = "$(R_HOME)/bin/Rscript -e "RcppThread::LdFlags()"`, but when I submitted it to CRAN for automated checks, Debian reported 1 WARNING: `Compilation used the following non-portable flag(s): '-Wno-missing-template-arg-list-after-template-kw'`, while Windows did not. [One of my R packages](https://github.com/stscl/spEDM) that I worked on recently used the same configuration but did not show this warning. The new package suddenly has it, and I am quite confused. I am not sure how to fix this issue and would like to ask for your advice.

**Comment by tnagler** [comment]
The warning is about a compiler-specific compilation flag `no-missing-template-arg-list-after-template-kw'. This flag isn't set anywhere in RcppThread and, as far as I can see, also not in your package. Most commonly, such flags are set by the user/build system. So my guess is that this is a temporary issue with the CRAN build system that should be fixed within days.

**Comment by SpatLyu** [comment]
The issue was indeed related to the CRAN check, but it was resolved the next day. Thank you for your reply.
