### ISSUE TITLE
Travis installation issue

### ISSUE THREAD

**Issue by pommedeterresautee** [tnagler/RcppThread#8]
During the installation of RcppThread, Travis crash.
It works on Windows and AppVeyor.

Here is the report:
https://travis-ci.org/pommedeterresautee/fastrtext

AppVeyor (working)
https://ci.appveyor.com/project/pommedeterresautee/fastrtext

Description file:
https://github.com/pommedeterresautee/fastrtext/blob/master/DESCRIPTION

Is there something else to do to make Travis work

**Comment by tnagler** [comment]
Yeah, unfortunately gcc's default version on travis is not fully C++11 compatible, so you need to install a newer one. Just put this block in your `.travis.yml`:
```
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-4.9 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 100
```

**Comment by pommedeterresautee** [comment]
Again, it works! Thanks a lot!!

**Comment by pommedeterresautee** [comment]
Just FYI it seems Rhub service doesn't support RcppThread. This should appear in the README (if I am right of course).

**Comment by tnagler** [comment]
What's the error message you're getting?

**Comment by pommedeterresautee** [comment]
https://builder.r-hub.io/status/fastrtext_0.2.2.tar.gz-b79d0a972efa4cef9e5358b06f79dda7

**Comment by tnagler** [comment]
Yeah, not sure if this is actually related to `RcppThread`. The r-hub log doesn't give a lot of information :/

**Comment by pommedeterresautee** [comment]
Tried Rhub last week and was working. However you are right the only thing I know is that Rcout is not found....
I saw you are using RcppThread in a package, did Rhub works with it?

**Comment by tnagler** [comment]
It didn't work, but for a different reason. It didn't download any dependencies and failed before it installed the library. r-hub often has very weird behavior :/

**Comment by pommedeterresautee** [comment]
I get this error on Rhub for Windows since I added RcppThread !!

**Comment by tnagler** [comment]
Seems to be somewhat specific to the linking options used on r-hub. Anyway #9 seems to fix it.

**Comment by tnagler** [comment]
Patched version is on CRAN now, will take a day or so for the windows binaries to be built.

**Comment by pommedeterresautee** [comment]
new version makes Windows compilation working (the issue was the installation of RcppThread).
There is no change for Linux compilation (the issue is Rcout missing)

**Comment by pommedeterresautee** [comment]
Mmmhhh, CRAN has updated its checks, it doesn't work for Mac also
https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/fastrtext-00install.html
Same reason than Rhub, Rcout not found...
I will try some tests to evaluate the cause....

**Comment by tnagler** [comment]
Can you try with a
``` cpp
namespace std {
  RcppThread::RPrinter Rcout = RcppThread::RPrinter();
}
```
added to your `r_compliance.cc` ?

**Comment by pommedeterresautee** [comment]
Works on Rhub! Trying to push on Cran. I let you know. Thanks a lot, again!
